
package gui;

import Interfaces.IDetalleVenta;
import Interfaces.IDetalleVentaController;
import Interfaces.IProducto;
import Interfaces.IVenta;
import Interfaces.IVentaController;
import java.rmi.RemoteException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectormicliente.RMI;

public class PanelAgregarVenta extends javax.swing.JPanel {

    private JDialog dialogParent;
    private IProducto PRODUCTO = null;
    private int VENTAID;
    private double SUBTOTAL;
    private double IVA; 
    private double TOTAL;
    private int CONTADOR = 1;
    private DecimalFormat df = new DecimalFormat("#.00");
    private SimpleDateFormat SDF = new SimpleDateFormat("dd-MM-yyyy");
    
    public PanelAgregarVenta(JDialog dialogParent){
        initComponents();
        this.dialogParent = dialogParent;
        setFolioyVenta();
        inputContador.setText(String.valueOf(CONTADOR));
        refrescarTabla();
    }
    
    public void setFolioyVenta(){
        int numVentas;
        try {
            numVentas = RMI.getIVentaController().getNumVentas() + 1;
            //Obtenemos el numero de ventas y le sumamos uno al total
            VENTAID = numVentas;
            inputFolio.setText( "10" + String.valueOf(numVentas) );
        } catch (RemoteException ex) {
            Logger.getLogger(PanelAgregarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void refrescarTabla(){
        try {
            Vector<Vector> datos = new Vector<>();
            List<IProducto> lista;
            
            lista = RMI.getIProductoController().list();
            
            for( IProducto producto : lista ){
                Vector registro = new Vector();
                registro.add( producto.getProductoId());
                registro.add( producto.getCodigo());
                registro.add( producto.getMarca());
                registro.add( producto.getNombre());
                registro.add( producto.getPrecio());
                
                datos.add( registro );
            }
            
            Vector<String> columnas = new Vector<>();
            columnas.add("ProductoId");
            columnas.add("Codigo");
            columnas.add("Marca");
            columnas.add("Nombre");
            columnas.add("Precio");
            tablaProductos.setModel( new DefaultTableModel(datos, columnas));
        } catch (RemoteException ex) {
            Logger.getLogger(PanelAgregarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFolio = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new RSMaterialComponent.RSTableMetro();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputSubtotal = new RSMaterialComponent.RSTextFieldTwo();
        inputIVA = new RSMaterialComponent.RSTextFieldTwo();
        inputTOTAL = new RSMaterialComponent.RSTextFieldTwo();
        btnRestarContador = new RSMaterialComponent.RSButtonIconOne();
        btnSumarContador = new RSMaterialComponent.RSButtonIconOne();
        inputContador = new javax.swing.JTextField();
        btnCrearVenta = new RSMaterialComponent.RSButtonMaterialOne();

        setBackground(new java.awt.Color(255, 255, 255));

        inputFolio.setForeground(new java.awt.Color(0, 0, 0));
        inputFolio.setToolTipText("Ingrese un número que sera el folio de la venta");
        inputFolio.setEnabled(false);
        inputFolio.setFocusable(false);
        inputFolio.setPhColor(new java.awt.Color(153, 153, 153));
        inputFolio.setPlaceholder("Ingrese un folio");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Folio:");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductos.setBackgoundHead(new java.awt.Color(100, 181, 246));
        tablaProductos.setColorBorderHead(new java.awt.Color(255, 255, 255));
        tablaProductos.setColorBorderRows(new java.awt.Color(255, 255, 255));
        tablaProductos.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tablaProductos.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("SubTotal:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("IVA:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel5.setText("__________________________________________");
        jLabel5.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Total:");

        inputSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        inputSubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputSubtotal.setText("0.00");
        inputSubtotal.setBorderColor(new java.awt.Color(204, 204, 204));
        inputSubtotal.setEnabled(false);
        inputSubtotal.setFocusable(false);

        inputIVA.setForeground(new java.awt.Color(0, 51, 51));
        inputIVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputIVA.setText("0.00");
        inputIVA.setBorderColor(new java.awt.Color(204, 204, 204));
        inputIVA.setEnabled(false);
        inputIVA.setFocusable(false);
        inputIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIVAActionPerformed(evt);
            }
        });

        inputTOTAL.setForeground(new java.awt.Color(0, 0, 0));
        inputTOTAL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputTOTAL.setText("0.00");
        inputTOTAL.setBorderColor(new java.awt.Color(204, 204, 204));
        inputTOTAL.setEnabled(false);
        inputTOTAL.setFocusable(false);

        btnRestarContador.setBackground(new java.awt.Color(0, 204, 102));
        btnRestarContador.setBackgroundHover(new java.awt.Color(0, 157, 103));
        btnRestarContador.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REMOVE);
        btnRestarContador.setSizeIcon(20.0F);
        btnRestarContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarContadorActionPerformed(evt);
            }
        });

        btnSumarContador.setBackground(new java.awt.Color(0, 204, 102));
        btnSumarContador.setBackgroundHover(new java.awt.Color(0, 175, 103));
        btnSumarContador.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnSumarContador.setSizeIcon(20.0F);
        btnSumarContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarContadorActionPerformed(evt);
            }
        });

        inputContador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputContador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputContador.setText("0");
        inputContador.setEnabled(false);
        inputContador.setFocusable(false);
        inputContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputContadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRestarContador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputContador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSumarContador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(inputSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                    .addComponent(inputSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(btnRestarContador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSumarContador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputContador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCrearVenta.setBackground(new java.awt.Color(100, 181, 246));
        btnCrearVenta.setText("Confirmar Venta");
        btnCrearVenta.setToolTipText("");
        btnCrearVenta.setBackgroundHover(new java.awt.Color(100, 157, 249));
        btnCrearVenta.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnCrearVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputFolio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addComponent(btnCrearVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIVAActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        setearProducto();
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void btnSumarContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarContadorActionPerformed
        inputContador.setText( String.valueOf( ++CONTADOR ) );
        actualizarPrecios();
    }//GEN-LAST:event_btnSumarContadorActionPerformed

    private void btnRestarContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarContadorActionPerformed
        CONTADOR = (CONTADOR<= 1) ? 1 : CONTADOR-1;
        inputContador.setText( String.valueOf( CONTADOR ) );
        actualizarPrecios();
    }//GEN-LAST:event_btnRestarContadorActionPerformed

    private void btnCrearVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVentaActionPerformed
        try {
            //System.out.println( Integer.parseInt( inputFolio.getText() ) );
            
            IVenta venta = RMI.getIVentaController().newInstance();
            
            if( SUBTOTAL == 0){
                 JOptionPane.showMessageDialog(
                        this, 
                        "Seleccione un producto primero.",
                        "Imposible crear Venta",
                        JOptionPane.ERROR_MESSAGE);
                 return;
            }else{
                venta.setEstado(1);
                venta.setFecha(SDF.format(new Date()));
                venta.setFolio( Integer.parseInt(inputFolio.getText()) );
                venta.setIva(IVA);
                venta.setSubTotal(SUBTOTAL);
                venta.setTotal(TOTAL);
                venta.setVentaId( VENTAID );
                
                int resp = RMI.getIVentaController().add(venta);
                //creamos el detalleVenta
                int resp2 = setDetalleVenta( venta );
                
                if( resp == IVentaController.ADD_EXITO &&
                    resp2 == IDetalleVentaController.ADD_EXITO){
                        JOptionPane.showMessageDialog(
                        this, 
                        "Venta agregada con éxito.",
                        "Operacion exitosa",
                        JOptionPane.INFORMATION_MESSAGE);
                dialogParent.dispose();
                refrescarTabla();
                
                }else if( resp == IVentaController.ADD_SIN_EXITO ||
                          resp2 == IDetalleVentaController.ADD_SIN_EXITO){
                        JOptionPane.showMessageDialog(
                        this, 
                        "No fue posible completar la operación",
                        "Operación no completada",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (RemoteException ex) {
            Logger.getLogger(PanelAgregarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCrearVentaActionPerformed

    private void inputContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputContadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputContadorActionPerformed

    public int setDetalleVenta(IVenta venta){
        int respuesta = 0;
        try {
            IDetalleVenta detalle = RMI.getIDetalleVentaController().newInstance();
            
            detalle.setDetalleVentaId(VENTAID);
            detalle.setProductoId(PRODUCTO.getProductoId());
            detalle.setVentaId(VENTAID);
            detalle.setUnidades(CONTADOR);
            detalle.setPrecioUnidad(PRODUCTO.getPrecio());
            detalle.setTotal(SUBTOTAL);
            
            respuesta = RMI.getIDetalleVentaController().add(detalle);
            
        } catch (RemoteException ex) {
            Logger.getLogger(PanelAgregarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            return respuesta;
        }
    }
    private void actualizarPrecios(){
        try {
            SUBTOTAL = CONTADOR * PRODUCTO.getPrecio();
            IVA = SUBTOTAL * 0.16;
            TOTAL = SUBTOTAL + IVA;
            
            inputSubtotal.setText(df.format(SUBTOTAL));
            inputIVA.setText(df.format(IVA));
            inputTOTAL.setText(df.format(TOTAL));
        } catch (RemoteException ex) {
            Logger.getLogger(PanelAgregarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setearProducto(){
        try {
            int filaSelec = tablaProductos.getSelectedRow();
            if ( filaSelec == -1 ){
                return;
            }
            
            int productoID = (Integer) tablaProductos.getValueAt(filaSelec, 0);
            PRODUCTO = RMI.getIProductoController().findOne(productoID);
            
            actualizarPrecios();
        } catch (RemoteException ex) {
            Logger.getLogger(PanelAgregarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialOne btnCrearVenta;
    private RSMaterialComponent.RSButtonIconOne btnRestarContador;
    private RSMaterialComponent.RSButtonIconOne btnSumarContador;
    private javax.swing.JTextField inputContador;
    private RSMaterialComponent.RSTextFieldMaterial inputFolio;
    private RSMaterialComponent.RSTextFieldTwo inputIVA;
    private RSMaterialComponent.RSTextFieldTwo inputSubtotal;
    private RSMaterialComponent.RSTextFieldTwo inputTOTAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSTableMetro tablaProductos;
    // End of variables declaration//GEN-END:variables
}
